### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#11]
I found another parsing error.

```
2016-03-31 13:28:23 [scrapy] ERROR: Spider error processing <GET https://www.okcupid.com/profile/Lkngfrlov/questions> (referer: https://www.okcupid.com/profile/Lkngfrlov/personality)
Traceback (most recent call last):
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
    for x in result:
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 303, in parse_questions
    target_info = self.get_question_res(response.meta['user_name'], response.meta['target_info'], response)
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 324, in get_question_res
    answer = question.xpath(".//p[contains(@class, 'target')]//span[1]/text()")[0].extract().strip()
IndexError: list index out of range
```

**Comment by Deleetdk** [comment]
If we look at the page, we see the problem:

https://www.okcupid.com/profile/Lkngfrlov/questions

The user has no answers at all.

![no answers](https://cloud.githubusercontent.com/assets/6759913/14418539/9e2e988a-ffbf-11e5-8c33-522135d38dbf.png)

I added a try block to solve this problem.

```
            #try block, catches if the user has no answers at all
            try:
                answer = question.xpath(".//p[contains(@class, 'target')]//span[1]/text()")[0].extract().strip()
                temp = question.xpath("./@data-qid")
            except:
                return target_info
```

Testing it. First scraping:

```
Starting to scrapy Lkngfrlov's data.

Scraping basic data from https://www.okcupid.com/profile/Lkngfrlov?cf=regular

Downloading user images...

Scraping personality data from https://www.okcupid.com/profile/Lkngfrlov/personality

Saving user Lkngfrlov with 0 questions
```

Second scraping:

```
Starting to scrapy Lkngfrlov's data.

Scraping basic data from https://www.okcupid.com/profile/Lkngfrlov?cf=regular

Lkngfrlov is skipped.
```

Fixed in https://github.com/Deleetdk/OKCubot2/commit/c99154bead91a97ba68f871e3955c95de74b81f9
