### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#5]
Most scrapings do not give errors, but I found one that did:

```
2016-03-29 14:59:00 [scrapy] ERROR: Spider error processing <GET https://www.okcupid.com/profile/LukaBGesserit?cf=regular> (referer: https://www.okcupid.com/home)
Traceback (most recent call last):
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
    for x in result:
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 192, in parse_user_info
    target_info = self.parse_misc(response.meta["user_name"], target_info, response)
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 403, in parse_misc
    misc = response.xpath("//table[contains(@class, 'misc')]//td[2]/text()")[0].extract().strip().split(",")
IndexError: list index out of range
```

From looking at the profile https://www.okcupid.com/profile/LukaBGesserit it looks fairly normal to me. The only thing I noticed is that the user has not filled out his information re. smoking etc. (i.e. the third block in the profile, top right area).

**Comment by tomwalter2287** [comment]
OK.
I will fix it.

I assume some parts must be in html including misc.

**Comment by tomwalter2287** [comment]
I fix this problem with the following code.

# check whether there is a misc part

```
if len(misc) > 0:
    misc = misc[0].extract().strip().split(",")
else:
    return
```

**Comment by tomwalter2287** [comment]
I solved this problem. See the previous comment, pls.

**Comment by Deleetdk** [comment]
This user still gives an error.

```
2016-03-30 20:07:06 [scrapy] ERROR: Spider error processing <GET https://www.okcupid.com/profile/LukaBGesserit?cf=regular> (referer: https://www.okcupid.com/home)
Traceback (most recent call last):
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
    for x in result:
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 206, in parse_user_info
    target_info = self.parse_ideal_person(response.meta["user_name"], target_info, response)
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 493, in parse_ideal_person
    target_info.append(self.get_info_element(user_name, "lf_location", "near me"))
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by tomwalter2287** [comment]
I pushed new version.

I fixed this issue in that version.

**Comment by Deleetdk** [comment]
Confirmed that it works for me as well.

**Comment by tomwalter2287** [comment]
Good
