### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by Deleetdk** [Deleetdk/OKCubot2#9]
You have introduced a bug. Please test the program before you push to the repository.

```
2016-03-31 00:33:25 [scrapy] ERROR: Spider error processing <GET https://www.okcupid.com/profile/LukaBGesserit/questions> (referer: https://www.okcupid.com/home)
Traceback (most recent call last):
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 28, in process_spider_output
    for x in result:
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/env/local/lib/python2.7/site-packages/scrapy/spidermiddlewares/depth.py", line 54, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/mint/Desktop/OKCubot2/OKCubot2/OKcu/spiders/okcubot_spider.py", line 188, in check_skip
    with open(path, "rb") as f:
IOError: [Errno 2] No such file or directory: 'data//users.csv'
```

**Comment by tomwalter2287** [comment]
Hello, Emil!

Your feed back might ruin my upwork career.
Can you change the feed back for me?
I don't the extra money and I really want to get good feed back.

Please!

**Comment by tomwalter2287** [comment]
Hello?

**Comment by tomwalter2287** [comment]
I pushed new version

I believe it solves all open issues.

**Comment by Deleetdk** [comment]
I tested and it works for me now.
